flowchart TD
    subgraph ESP[ESP32 Microcontroller]
        direction TB
        subgraph L1[<b>Physical Interface Layer</b>]
            direction TB
            
            ESP_Board[I2s Interface]
            ESP_Mic[Microphones]
            ESP_Board -- "record audio" --> ESP_Mic
        end

        subgraph L2[<b>Communication Layer</b>]
            direction LR
            ESP_MQTT[SPI]
            ESP_BUFFERREADER[DMA Buffer]
        end

        subgraph L3[<b>Processing Layer</b>]
            
            ESP_Sampling[Audio Sampling]
        end
    end

    L3 ~~~~ L2 ~~~~ L1

    ESP_BUFFERREADER -- "Store data" --> ESP_Board
    ESP_MQTT -- "Queues audio batches" --> ESP_Sampling
    ESP_Sampling -- "Audio Data" --> ESP_BUFFERREADER
    