flowchart LR
    subgraph RPI[Raspberry Pi]
        
        subgraph L1[<b>Layer 4: Physical/motor control</b>]
            
            
            PI_Board[OpenCR board]
            PI_MC[Motor Controller]
            PI_Mot[Motor Interface]
            PI_Board -- "controls" --- PI_MC -- "PWM signals" --- PI_Mot
        end
        subgraph L2[<b>Layer 3: Communication</b>]
            PI_OPENCR[Turtlebot3 driver]
            PI_MQTT[MQTT Broker]
            PI_ROS[ROS Daemon]
            PI_Client[Mosquitto Client]
        end
        subgraph L3[<b>Layer 2: Processing layer</b>]
            
            PI_Bridge[MQTT-ROS Bridge]
        end
    end
    PI_OPENCR -- "Motor velocity" --- PI_Board
    PI_Client -- "subscribes Motor velocity" --- PI_MQTT
    PI_Bridge -- "positional commands" --- PI_Client
    PI_Bridge -- "publishes <br> Motor velocity" --- PI_ROS
    PI_ROS -- "subscribes <br> Motor velocity" --- PI_OPENCR

    PI_Bridge -- "subscribes: <br> Joint state" --- PI_ROS
    PI_ROS -- "publishes: <br> Joint state" --- PI_OPENCR
    PI_OPENCR -- "Joint state" --- PI_Board
    